"""Add images table for user image storage

Revision ID: 10c296da2f4f
Revises: 7edd80948858
Create Date: 2025-09-26 15:18:19.345001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c296da2f4f'
down_revision = '7edd80948858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('compressed_url', sa.String(), nullable=False),
    sa.Column('thumbnail_urls', sa.JSON(), nullable=False),
    sa.Column('platform_optimized_urls', sa.JSON(), nullable=True),
    sa.Column('storage_paths', sa.JSON(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###